// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


export const GET_ALL_BLOG = 'GET_ALL_BLOG';
export const GET_ALL_BLOG_SUCCESS = 'GET_ALL_BLOG_SUCCESS';
export const GET_ALL_BLOG_FAIL = 'GET_ALL_BLOG_FAIL';

export const GET_ONE_BLOG = 'GET_ONE_BLOG';
export const GET_ONE_BLOG_SUCCESS = 'GET_ONE_BLOG_SUCCESS';
export const GET_ONE_BLOG_FAIL = 'GET_ONE_BLOG_FAIL';

export const CREATE_BLOG = 'CREATE_BLOG';
export const CREATE_BLOG_SUCCESS = 'CREATE_BLOG_SUCCESS';
export const CREATE_BLOG_FAIL = 'CREATE_BLOG_FAIL';

export const UPDATE_BLOG = 'UPDATE_BLOG';
export const UPDATE_BLOG_SUCCESS = 'UPDATE_BLOG_SUCCESS';
export const UPDATE_BLOG_FAIL = 'UPDATE_BLOG_FAIL';

export const DELETE_BLOG = 'DELETE_BLOG';
export const DELETE_BLOG_SUCCESS = 'DELETE_BLOG_SUCCESS';
export const DELETE_BLOG_FAIL = 'DELETE_BLOG_FAIL';

