// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


export const GET_ALL_BLOGTYPE = 'GET_ALL_BLOGTYPE';
export const GET_ALL_BLOGTYPE_SUCCESS = 'GET_ALL_BLOGTYPE_SUCCESS';
export const GET_ALL_BLOGTYPE_FAIL = 'GET_ALL_BLOGTYPE_FAIL';

export const GET_ONE_BLOGTYPE = 'GET_ONE_BLOGTYPE';
export const GET_ONE_BLOGTYPE_SUCCESS = 'GET_ONE_BLOGTYPE_SUCCESS';
export const GET_ONE_BLOGTYPE_FAIL = 'GET_ONE_BLOGTYPE_FAIL';

export const CREATE_BLOGTYPE = 'CREATE_BLOGTYPE';
export const CREATE_BLOGTYPE_SUCCESS = 'CREATE_BLOGTYPE_SUCCESS';
export const CREATE_BLOGTYPE_FAIL = 'CREATE_BLOGTYPE_FAIL';

export const UPDATE_BLOGTYPE = 'UPDATE_BLOGTYPE';
export const UPDATE_BLOGTYPE_SUCCESS = 'UPDATE_BLOGTYPE_SUCCESS';
export const UPDATE_BLOGTYPE_FAIL = 'UPDATE_BLOGTYPE_FAIL';

export const DELETE_BLOGTYPE = 'DELETE_BLOGTYPE';
export const DELETE_BLOGTYPE_SUCCESS = 'DELETE_BLOGTYPE_SUCCESS';
export const DELETE_BLOGTYPE_FAIL = 'DELETE_BLOGTYPE_FAIL';

