// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System.Linq;
using SQ.Core.Data;
using GG.Data.Models;
using System.Threading.Tasks;

namespace GG.Data.Service
{
	public interface IBlogService
    {
		Task<int> DeleteAsync(Blog entity);

        IPagedList<Blog> GetPageList(int pageIndex, int pageSize);

        Task<int> InsertAsync(Blog entity);

        Task<int> UpdateAsync(Blog entity);

        IQueryable<Blog> GetAll();

        Task<Blog> FindOneAsync(int Id);	
    }
}
