// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System.Linq;
using SQ.Core.Data;
using GG.Data.Models;
using System.Threading.Tasks;

namespace GG.Data.Service
{
	public interface IBlogTypeService
    {
		Task<int> DeleteAsync(BlogType entity);

        IPagedList<BlogType> GetPageList(int pageIndex, int pageSize);

        Task<int> InsertAsync(BlogType entity);

        Task<int> UpdateAsync(BlogType entity);

        IQueryable<BlogType> GetAll();

        Task<BlogType> FindOneAsync(int Id);	
    }
}
