// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using SQ.Core.Data;
using GG.Data.Service;
using GG.Data.Models;
using System.Threading.Tasks;

namespace GG.Data.Impl
{
	public class BlogService : IBlogService
    {
		   #region Fields

        private readonly IRepository<Blog> _BlogRepository;

        #endregion

        #region Ctor

        public BlogService(IRepository<Blog> BlogRepository
           )
        {
            this._BlogRepository = BlogRepository;

        }
        #endregion

        public async Task<int> DeleteAsync(Blog entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Blog");

            entity.Deleted = true;
           return await UpdateAsync(entity);
        }

        public async Task<Blog> FindOneAsync(int Id)
        {
            if (Id == 0)
                return null;

            var entity = await _BlogRepository.GetByIdAsync(Id);
            return entity;
        }

        public IQueryable<Blog> GetAll()
        {
            return _BlogRepository.Table;
        }

        public IPagedList<Blog> GetPageList(int pageIndex, int pageSize)
        {
            var query = _BlogRepository.Table;
            query = query.OrderByDescending(a => a.Id);
            var result = new PagedList<Blog>(query, pageIndex, pageSize);
            return result;
        }

        public async Task<int> InsertAsync(Blog entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Blog");
            return await _BlogRepository.InsertAsync(entity);
        }

        public async Task<int> UpdateAsync(Blog entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Blog");

            return await _BlogRepository.UpdateAsync(entity);
        }
    }
}
