// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


import * as blogTypes from '../contants/blog';

export function getAll() {
  return {
    types: [blogTypes.GET_ALL_BLOG, blogTypes.GET_ALL_BLOG_SUCCESS, blogTypes.GET_ALL_BLOG_FAIL],
    promise: (client) => client.get('/blog',{
      token: true
    })
  };
}

export function getById(id) {
  return {
    types: [blogTypes.GET_ONE_BLOG, blogTypes.GET_ONE_BLOG_SUCCESS, blogTypes.GET_ONE_BLOG_FAIL],
    promise: (client) => client.get('/blog'+id,{
      token: true
    })
  };
}

export function create(data) {
  return {
    types: [blog.CREATE_BLOG, blog.CREATE_BLOG_SUCCESS, blog.CREATE_BLOG_FAIL],
    promise: (client) => client.post('/blog', {
      data: data,
	  token: true
    })
  };
}

export function update(id, data) {
  return {
    types: [blog.UPDATE_BLOG, blog.UPDATE_BLOG_SUCCESS, blog.UPDATE_BLOG_FAIL],
    promise: (client) => client.put('/blog/'+id, {
      data: data,
	  token: true
    })
  };
}

export function delete(id) {
  return {
    types: [blog.DELETE_BLOG, blog.DELETE_BLOG_SUCCESS, blog.DELETE_BLOG_FAIL],
    promise: (client) => client.delete('/blog/'+id, {
		token: true
    })
  };
}

