// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using FluentValidation;
using GG.Data.DTO;

namespace GG.Data.Validator
{
    public class BlogTypeValidator : AbstractValidator<BlogTypeDTO>
    {
        public BlogTypeValidator()
        {
            //RuleFor(BlogType => BlogType.Name).NotNull().WithMessage("{PropertyName} is required");
        }
    }
}

