// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using GG.Data.Models;

namespace GG.Data.DTO
{
	public class BlogTypeDTO
    {
         
       public string CateName  { get; set; } 
       public int? PID  { get; set; } 
       public string Code  { get; set; } 
       public int Level  { get; set; } 
       public string UserId  { get; set; } 
       public int Id  { get; set; } 
    }
}
