// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using GG.Data.Models;

namespace GG.Data.DTO
{
	public class UserActivitiesDTO
    {
         
       public DateTime Time  { get; set; } 
       public string UserId  { get; set; } 
       public UserActivityType Type  { get; set; } 
       public int Id  { get; set; } 
    }
}
