// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using AutoMapper;
using SQ.Core.AutoMapper;
using GG.Data.Models;
using GG.Data.DTO;

namespace GG.Data.AutoMapper
{
    public class BlogProfile : BaseProfile
    {
        public BlogProfile() : base("BlogProfile")
        {
        }

        protected override void CreateMaps()
        {

            CreateMap<Blog, BlogDTO>()
                .ForMember(dto => dto.BlogTypeName, o => o.MapFrom(entity => entity.BlogType.CateName))
;


            CreateMap<BlogDTO, Blog>()
    .ForMember(entity => entity.BlogType, o => o.Ignore())
    .ForMember(entity => entity.ApplicationUser, o => o.Ignore())
    ;
        }
    }
}
