// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using AutoMapper;
using SQ.Core.AutoMapper;
using GG.Data.Models;
using GG.Data.DTO;

namespace GG.Data.AutoMapper
{
    public class BlogTypeProfile : BaseProfile
    {
        public BlogTypeProfile() : base("BlogTypeProfile")
        {
        }

        protected override void CreateMaps()
        {

            CreateMap<BlogType, BlogTypeDTO>();


            CreateMap<BlogTypeDTO, BlogType>()
                .ForMember(entity => entity.Deleted, o => o.Ignore())
                .ForMember(entity => entity.PCate, o => o.Ignore())
                .ForMember(entity => entity.ChildCates, o => o.Ignore())
                .ForMember(entity => entity.Blog, o => o.Ignore())
                .ForMember(entity => entity.ApplicationUser, o => o.Ignore());
        }
    }
}
