// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using AutoMapper;
using SQ.Core.AutoMapper;
using GG.Data.Models;
using GG.Data.DTO;

namespace GG.Data.AutoMapper
{
	public class UserActivitiesProfile : BaseProfile
    {
        public UserActivitiesProfile() : base("UserActivitiesProfile")
        {
        }

		protected override void CreateMaps()
        {
			 
			CreateMap<UserActivities, UserActivitiesDTO>()
;

			 
        CreateMap<UserActivitiesDTO, UserActivities>()
.ForMember(entity => entity.ApplicationUser, o => o.Ignore())
;
        }
    }
}
