// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


import * as blogTypeTypes from '../contants/blogType';

const initialState = {
};

export default function blogType(state = initialState, action = {}) {
	switch (action.type) {
		case authTypes.GET_ALL_BLOGTYPE:
		case authTypes.GET_ONE_BLOGTYPE:
		case authTypes.CREATE_BLOGTYPE:
		case authTypes.UPDATE_BLOGTYPE:
		case authTypes.DELETE_BLOGTYPE:
			return {
				...state,
				loading: true
			};
		case authTypes.GET_ALL_BLOGTYPE_FAIL:
		case authTypes.GET_ONE_BLOGTYPE_FAIL:
		case authTypes.CREATE_BLOGTYPE_FAIL:
		case authTypes.UPDATE_BLOGTYPE_FAIL:
		case authTypes.DELETE_BLOGTYPE_FAIL:
			return {
				...state,
				loading: false,
				error: action.error
			};
		case authTypes.GET_ALL_BLOGTYPE_SUCCESS:
			return {
				...state,
				loading: false,
				list: action.result
			};
		case authTypes.GET_ONE_BLOGTYPE_SUCCESS:
			return {
				...state,
				loading: false,
				entity: action.result
			};
		case authTypes.CREATE_BLOGTYPE_SUCCESS:
			return {
				...state,
				loading: false,
				entity: action.result
			};
		case authTypes.UPDATE_BLOGTYPE_SUCCESS:
			return {
				...state,
				loading: false,
				entity: action.result
			};
		case authTypes.DELETE_BLOGTYPE_SUCCESS:
			return {
				...state,
				loading: false,
				entity: action.result
			};
		default:
			return state;
  }
}

