// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


import * as blogTypes from '../contants/blog';

const initialState = {
};

export default function blog(state = initialState, action = {}) {
	switch (action.type) {
		case authTypes.GET_ALL_BLOG:
		case authTypes.GET_ONE_BLOG:
		case authTypes.CREATE_BLOG:
		case authTypes.UPDATE_BLOG:
		case authTypes.DELETE_BLOG:
			return {
				...state,
				loading: true
			};
		case authTypes.GET_ALL_BLOG_FAIL:
		case authTypes.GET_ONE_BLOG_FAIL:
		case authTypes.CREATE_BLOG_FAIL:
		case authTypes.UPDATE_BLOG_FAIL:
		case authTypes.DELETE_BLOG_FAIL:
			return {
				...state,
				loading: false,
				error: action.error
			};
		case authTypes.GET_ALL_BLOG_SUCCESS:
			return {
				...state,
				loading: false,
				list: action.result
			};
		case authTypes.GET_ONE_BLOG_SUCCESS:
			return {
				...state,
				loading: false,
				entity: action.result
			};
		case authTypes.CREATE_BLOG_SUCCESS:
			return {
				...state,
				loading: false,
				entity: action.result
			};
		case authTypes.UPDATE_BLOG_SUCCESS:
			return {
				...state,
				loading: false,
				entity: action.result
			};
		case authTypes.DELETE_BLOG_SUCCESS:
			return {
				...state,
				loading: false,
				entity: action.result
			};
		default:
			return state;
  }
}

